title: KiCad Libraries
url: "https://kicad.org"
github_username:  KiCad
description: KiCad Libraries

encoding: UTF-8

# Build settings
theme: minima

collections:
  symbols:
    output: true
  footprints:
    output: true
  packages3d:
    output: true