title: KiCad Libraries
url: "http://kicad-pcb.org"
github_username:  KiCad
description: KiCad Libraries

# Build settings
theme: minima

collections:
  symbols:
    output: true
  footprints:
    output: true
  packages3d:
    output: true